export const sample_foods = [
  {
    id: '1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Pizza de Marguerita',
    price: 20,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '4',
    name: 'X Tudao',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['germany', 'us'],
    stars: 3,
    imageUrl: 'food-4.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '5',
    name: 'Temaki',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['japao'],
    stars: 3.5,
    imageUrl: 'food-5.jpg',
    tags: ['Japa'],
  },
  {
    id: '6',
    name: 'Hot-Holl',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['japao'],
    stars: 4.0,
    imageUrl: 'food-6.jpg',
    tags: ['Japa'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: true,
  },
];
